### PR TITLE
Improves compact output for @page at-rule

### PR DESCRIPTION
**Pull request by leonsenft**
Also adds test cases to verify compact output of other at-rules is optimal.

### CODE REVIEW

**Review by kevmoo — APPROVED** [review]
pubspec and changelog bumps?

**Comment by leonsenft** [comment]
My bad, totally forgot to update the change log.

@kevmoo let's merge this, then rebase #65 on top and update the version and publish.

**Review by kevmoo — COMMENTED** [review]
Per convention, update pubspec version to `0.14.4-dev` and then add that entry to the changelog.

Unless you want to release this now. Then just call it `0.14.4`

**Comment by kevmoo** [comment]
@leonsenft – saw your comment. SGTM

**Pull request merged**
