### PR TITLE
Update test expectations for source_span output

### PR DESCRIPTION
**Pull request by natebosch**
Version `1.5.0` of `source_span` changed the output format. Update the
tests which hardcoded the expected output to the new format.

### CODE REVIEW

**Review by leonsenft — APPROVED** [review]

**Comment by leonsenft** [comment]
Thanks!

**Comment by leonsenft** [comment]
@natebosch Oops, actually we should have updated the lower bound on package:source_span right? The existing constraint would allow an older version in which the tests would fail.

**Comment by natebosch** [comment]
Yes it would allow it. The problem would be solved with a `pub upgrade` and only impacts authors of this package.

For stuff that doesn't impact downstream consumers I typically avoid unnecessarily bumping the minimum version. Pub doesn't have the capability to express that the "dev_dependency" portion is more restricted than the general "dependency" portion of a package...

**Comment by kevmoo** [comment]
If anyone is bored, pkg:http has the same issue...

**Pull request merged**
