### PR TITLE
Remove upper case constants

### PR DESCRIPTION
**Pull request by lrhn**

### CODE REVIEW

**Review by kevmoo — COMMENTED** [review]
Remove stable from the travis config and we should be good...

**Comment by kevmoo** [comment]
...and rebase 😄

**Comment by lrhn** [comment]
PTAL, and please publish when merged.

**Review by kevmoo — APPROVED** [review]

**Comment by leonsenft** [comment]
Moved here https://github.com/dart-lang/csslib/pull/71.

**Pull request closed without merging**
