### PR TITLE
Add return types and remove local variable types

### PR DESCRIPTION
**Pull request by natebosch**
The return types do, in some cases, change the interface of a public
API, but only to make it more descriptive of behavior. Only code that
would have had runtime errors should be statically impacted by the
change.

### CODE REVIEW

**Comment by kevmoo** [comment]
dartfmt? @natebosch

**Review by kevmoo — APPROVED** [review]
Assuming travis is green – thanks!

**Comment by natebosch** [comment]
😢 

This turned out to be breaking, some subclasses of `Visitor` actually rely on it being `dynamic`. What we really should have done from the beginning was use `Visitor<T>`.

**Comment by kevmoo** [comment]
Not surprising! Bleh...

**Comment by kevmoo** [comment]
Better to just ignore the lint for now and open an issue pointing to V2?

**Comment by natebosch** [comment]
> Better to just ignore the lint for now and open an issue pointing to V2?

It won't be very easy to fix in V2. People that `extends Visitor` rely on having _some_ values flow through, but that class only ever makes sense as a `BaseVisitor<void>` since it ignores a bunch of return values and can't return any value from some of its implemented methods. The use cases extending this class must just be avoiding any of the broken code paths.

It's still best practice to annotated a method that returns `dynamic` so I'll do that here. The poorly designed interface will have to stay for now.

**Pull request merged**
