### PR TITLE
Use explicit dynamic over void return types

### PR DESCRIPTION
**Pull request by natebosch**
Some implementations are relying on passing values through the visit
methods. Make return types explicitly `dynamic` to match their implicit
types from before.

This highlights that extending the `Visitor` class and expecting to return
useful values is inherently risky. Not only will usages fall through to dynamic
and have no static errors for things like typos, there are also places where
the values will be silently discarded by the implementation in` Visitor`.

### CODE REVIEW

**Comment by natebosch** [comment]
I'm going to try this with some internal code to see if it is still a breaking change - if it is we might need to make things explicitly `dynamic` everywhere.

**Comment by natebosch** [comment]
This was still breaking so I switch to marking a bunch of methods that were implicitly returning `dynamic` before https://github.com/dart-lang/csslib/pull/98 to have an explicit `dynamic` instead of `void`. Some methods do still statically return `void` because they aren't used as interfaces and so it's safe to be more precise.

**Review by jakemac53 — APPROVED** [review]
SGTM assuming internally it looks good

**Comment by natebosch** [comment]
Initial sample internally looks good. I'll avoid publishing  until it's fully verified.

**Pull request merged**
