### PR TITLE
Add support for exponential notation.

### PR DESCRIPTION
**Pull request by daohoangson**
Related to dart-lang/tools#1174

### CODE REVIEW

**Comment by kevmoo** [comment]
@devoncarew ?

**Comment by devoncarew** [comment]
Thanks for the contribution!

I don't see the css validating using the validator at https://jigsaw.w3.org/css-validator.

```
1		Value Error : color Unknown dimension 1e2
1		Value Error : color Unknown dimension .5e1
1		Value Error : color Unknown dimension .5e-1
1		Value Error : color Invalid RGB function )
```

That site claims to be validating against CSS level 3.

**Comment by devoncarew** [comment]
I do see exponential notation in the railroad grammar for numeric tokens (https://drafts.csswg.org/css-syntax-3/#typedef-number-token), and can use it in css properties when editing things in devtools. I wonder - is the validator out of date? Incorrect?

**Comment by daohoangson** [comment]
Apparently all popular validators fail to parse this. It works in both Chrome and Safari though.

https://jsfiddle.net/36r8vpas/

Screen Shot 2023-05-16 at 09 41 18

**Comment by devoncarew** [comment]
Hmm, @leonsenft - do you have thoughts here?

**Comment by mosuem** [comment]
Closing as the [dart-lang/csslib](https://github.com/dart-lang/csslib) repository is merged into the [dart-lang/tools](https://github.com/dart-lang/tools) monorepo. Please re-open this PR there!

**Pull request closed without merging**
